language: php

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.4

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

before_script:
  - phpenv config-rm xdebug.ini

script:
  - vendor/bin/phpunit
